# -*- coding: utf-8 -*-
"""Copia de Te damos la bienvenida a Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O4OF8fW7MC_3wU33Uan5ZdpYDZ3E3_WL

CELDA 1: Crear carpeta de Agentes
"""

import os

os.makedirs("agentes", exist_ok=True)
os.makedirs("data", exist_ok=True)

print("Estructura creada")

"""CELDA 2: Crear agente_normalizador.py"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile agentes/agente_normalizador.py
# 
# import pandas as pd
# 
# from sklearn.compose import ColumnTransformer
# from sklearn.pipeline import Pipeline
# 
# from sklearn.impute import SimpleImputer
# from sklearn.preprocessing import StandardScaler
# from sklearn.preprocessing import OneHotEncoder
# 
# 
# class AgenteNormalizador:
# 
#     def __init__(self):
# 
#         self.preprocessor = None
# 
#     def procesar(self, df, target):
# 
#         print("=== AGENTE 1: NORMALIZADOR ===")
# 
#         # Eliminar identificador si existe
#         if "Employee_ID" in df.columns:
#             df = df.drop(columns=["Employee_ID"])
#             print("✓ Employee_ID eliminado")
# 
#         # Separar variables
#         X = df.drop(columns=[target])
#         y = df[target]
# 
#         numericas = X.select_dtypes(
#             include=["int64", "float64"]
#         ).columns.tolist()
# 
#         categoricas = X.select_dtypes(
#             include=["object"]
#         ).columns.tolist()
# 
#         print(f"Variables numéricas: {len(numericas)}")
#         print(f"Variables categóricas: {len(categoricas)}")
# 
#         # Pipeline numérico
#         numeric_transformer = Pipeline(
#             steps=[
#                 (
#                     "imputer",
#                     SimpleImputer(strategy="median")
#                 ),
#                 (
#                     "scaler",
#                     StandardScaler()
#                 )
#             ]
#         )
# 
#         # Pipeline categórico
#         categorical_transformer = Pipeline(
#             steps=[
#                 (
#                     "imputer",
#                     SimpleImputer(strategy="most_frequent")
#                 ),
#                 (
#                     "encoder",
#                     OneHotEncoder(
#                         handle_unknown="ignore"
#                     )
#                 )
#             ]
#         )
# 
#         # Transformador principal
#         self.preprocessor = ColumnTransformer(
#             transformers=[
#                 (
#                     "num",
#                     numeric_transformer,
#                     numericas
#                 ),
#                 (
#                     "cat",
#                     categorical_transformer,
#                     categoricas
#                 )
#             ]
#         )
# 
#         X_procesado = self.preprocessor.fit_transform(X)
# 
#         print("✓ Imputación realizada")
#         print("✓ Escalado realizado")
#         print("✓ Codificación realizada")
# 
#         mensaje = {
#             "tipo": "dataset_limpio",
#             "datos": X_procesado,
#             "target": y
#         }
# 
#         return mensaje

"""CELDA 3: Verificar que se creo"""

!ls agentes

"""CELDA 4: Subir el dataseT"""

from google.colab import files

uploaded = files.upload()

"""CELDA 5: Probar el Agente"""

import pandas as pd

from agentes.agente_normalizador import AgenteNormalizador

df = pd.read_csv(
    "AI_Impact_on_Jobs_2030.csv"
)

agente1 = AgenteNormalizador()

mensaje = agente1.procesar(
    df,
    target="Hiring_Trend_2026"
)

"""CELDA 6: Ver lo que entrega al siguiente Agente"""

print(mensaje["tipo"])
print(mensaje["datos"].shape)
print(mensaje["target"].shape)