# -*- coding: utf-8 -*-
"""Copia de Copia de Copia de Te damos la bienvenida a Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HfmWfn75K_w4MjmXiTAS3fnb87c1XwLE

CELDA 1: Crear carpeta de Agentes
"""

import os

os.makedirs("agentes", exist_ok=True)
os.makedirs("data", exist_ok=True)

print("Estructura creada")

"""CELDA 2: Crear agente_normalizador.py"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile agentes/agente_normalizador.py
# 
# import pandas as pd
# 
# from sklearn.compose import ColumnTransformer
# from sklearn.pipeline import Pipeline
# 
# from sklearn.impute import SimpleImputer
# from sklearn.preprocessing import StandardScaler
# from sklearn.preprocessing import OneHotEncoder
# 
# 
# class AgenteNormalizador:
# 
#     def __init__(self):
# 
#         self.preprocessor = None
# 
#     def procesar(self, df, target):
# 
#         print("=== AGENTE 1: NORMALIZADOR ===")
# 
#         # Eliminar identificador si existe
#         if "Employee_ID" in df.columns:
#             df = df.drop(columns=["Employee_ID"])
#             print("✓ Employee_ID eliminado")
# 
#         # Separar variables
#         X = df.drop(columns=[target])
#         y = df[target]
# 
#         numericas = X.select_dtypes(
#             include=["int64", "float64"]
#         ).columns.tolist()
# 
#         categoricas = X.select_dtypes(
#             include=["object"]
#         ).columns.tolist()
# 
#         print(f"Variables numéricas: {len(numericas)}")
#         print(f"Variables categóricas: {len(categoricas)}")
# 
#         # Pipeline numérico
#         numeric_transformer = Pipeline(
#             steps=[
#                 (
#                     "imputer",
#                     SimpleImputer(strategy="median")
#                 ),
#                 (
#                     "scaler",
#                     StandardScaler()
#                 )
#             ]
#         )
# 
#         # Pipeline categórico
#         categorical_transformer = Pipeline(
#             steps=[
#                 (
#                     "imputer",
#                     SimpleImputer(strategy="most_frequent")
#                 ),
#                 (
#                     "encoder",
#                     OneHotEncoder(
#                         handle_unknown="ignore"
#                     )
#                 )
#             ]
#         )
# 
#         # Transformador principal
#         self.preprocessor = ColumnTransformer(
#             transformers=[
#                 (
#                     "num",
#                     numeric_transformer,
#                     numericas
#                 ),
#                 (
#                     "cat",
#                     categorical_transformer,
#                     categoricas
#                 )
#             ]
#         )
# 
#         X_procesado = self.preprocessor.fit_transform(X)
# 
#         print("✓ Imputación realizada")
#         print("✓ Escalado realizado")
#         print("✓ Codificación realizada")
# 
#         mensaje = {
#             "tipo": "dataset_limpio",
#             "datos": X_procesado,
#             "target": y
#         }
# 
#         return mensaje

"""CELDA 3: Verificar que se creo"""

!ls agentes

"""CELDA 4: Subir el dataseT"""

from google.colab import files

uploaded = files.upload()

"""CELDA 5: Probar el Agente"""

import pandas as pd

from agentes.agente_normalizador import AgenteNormalizador

df = pd.read_csv(
    "AI_Impact_on_Jobs_2030.csv"
)

agente1 = AgenteNormalizador()

mensaje = agente1.procesar(
    df,
    target="Hiring_Trend_2026"
)

"""CELDA 6: Ver lo que entrega al siguiente Agente"""

print(mensaje["tipo"])
print(mensaje["datos"].shape)
print(mensaje["target"].shape)

"""CELDA 7: Crear agente_entrenador.py"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile agentes/agente_entrenador.py
# import pandas as pd
# from sklearn.model_selection import train_test_split
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.linear_model import LogisticRegression
# from sklearn.metrics import accuracy_score
# 
# class AgenteEntrenador:
#     def __init__(self):
#         self.mejor_modelo = None
#         self.metricas = {}
# 
#     def procesar(self, mensaje_anterior):
#         print("\n=== AGENTE 2: ENTRENADOR DE MODELO ===")
#         X = mensaje_anterior["datos"]
#         y = mensaje_anterior["target"]
# 
#         # CORRECCIÓN AQUÍ: Cambiado test_split por test_size
#         X_train, X_test, y_train, y_test = train_test_split(
#             X, y, test_size=0.2, random_state=42
#         )
#         print("✓ Validación aplicada (Split 80/20)")
# 
#         modelos = {
#             "Regresión Logística": LogisticRegression(max_iter=1000),
#             "Random Forest": RandomForestClassifier(random_state=42)
#         }
# 
#         mejor_score = 0
#         nombre_mejor_modelo = ""
# 
#         for nombre, modelo in modelos.items():
#             modelo.fit(X_train, y_train)
#             preds = modelo.predict(X_test)
#             acc = accuracy_score(y_test, preds)
#             print(f"  - Evaluando {nombre}... Exactitud (Accuracy): {acc:.4f}")
# 
#             if acc > mejor_score:
#                 mejor_score = acc
#                 self.mejor_modelo = modelo
#                 nombre_mejor_modelo = nombre
# 
#         print(f"✓ Modelo seleccionado: {nombre_mejor_modelo} con {mejor_score:.4f} de exactitud")
# 
#         self.metricas = {
#             "nombre_modelo": nombre_mejor_modelo,
#             "exactitud": mejor_score
#         }
# 
#         mensaje_salida = {
#             "tipo": "metricas_modelo",
#             "modelo": self.mejor_modelo,
#             "metricas": self.metricas
#         }
# 
#         return mensaje_salida

"""CELDA 8: Verificar archivos en la carpeta agentes"""

!ls agentes

"""CELDA 9: Ejecutar el Agente Entrenador"""

import sys

# 1. Forzar la eliminación del agente con error de la memoria de Python
if "agentes.agente_entrenador" in sys.modules:
    del sys.modules["agentes.agente_entrenador"]

# 2. Ahora sí, importar la versión limpia y corregida del archivo
from agentes.agente_entrenador import AgenteEntrenador

# 3. Inicializar el Agente 2
agente2 = AgenteEntrenador()

# 4. Pasar el mensaje del Agente 1 (Normalizador)
mensaje_modelo = agente2.procesar(mensaje)

"""CELDA 10: Ver lo que entrega al siguiente Agente"""

print("=== VERIFICACIÓN DE SALIDA (AGENTE 2) ===")
print(f"Tipo de mensaje generado: {mensaje_modelo['tipo']}")
print(f"Algoritmo seleccionado:   {mensaje_modelo['metricas']['nombre_modelo']}")
print(f"Exactitud obtenida (Acc): {mensaje_modelo['metricas']['exactitud']:.4f}")
print("-" * 41)
print(f"Objeto del modelo listo:  {mensaje_modelo['modelo']}")

import os
os.makedirs("agentes", exist_ok=True)

"""CELDA 11: Crear agente_comunicador.py"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile agentes/agente_comunicador.py
# 
# class AgenteComunicador:
#     def procesar(self, mensaje_anterior):
#         print("\n=== AGENTE 3: COMUNICADOR ===")
# 
#         # Extraer los datos técnicos que dejó el Agente 2
#         metricas = mensaje_anterior["metricas"]
#         nombre_modelo = metricas["nombre_modelo"]
#         exactitud = metricas["exactitud"]
# 
#         print("✓ Traduciendo métricas a lenguaje natural...")
# 
#         # Redacción del reporte final formateado
#         reporte = f"""
# ======================================================================
#                   REPORTE FINAL DEL ANÁLISIS DE DATOS
# ======================================================================
# Tras procesar el flujo automático de agentes inteligentes, se exponen
# los siguientes hallazgos y resultados:
# 
# 1. Estado del Pipeline:
#    Se ha completado con éxito el procesamiento, entrenamiento y
#    validación de modelos predictivos sobre el dataset.
# 
# 2. Algoritmo Seleccionado:
#    El agente evaluador determinó que el modelo de '{nombre_modelo}'
#    presentó el desempeño más óptimo frente a los demás candidatos.
# 
# 3. Rendimiento Obtenido:
#    La métrica de exactitud (Accuracy) final es de {exactitud * 100:.2f}%.
# 
# Conclusión: El sistema de agentes completó el ciclo automatizado.
# El modelo base está listo. Se sugiere optimizar o balancear variables
# en futuras iteraciones para incrementar el porcentaje de acierto.
# ======================================================================
# """
#         return reporte

"""CELDA 12: Probar el Agente Comunicador"""

from agentes.agente_comunicador import AgenteComunicador

# Inicializamos el Agente 3
agente3 = AgenteComunicador()

# Le pasamos el resultado que guardó el agente 2 en la celda 9
reporte_final = agente3.procesar(mensaje_modelo)

# Imprimimos el reporte final en texto plano
print(reporte_final)