# -*- coding: utf-8 -*-
"""Copia de Te damos la bienvenida a Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O4OF8fW7MC_3wU33Uan5ZdpYDZ3E3_WL

CELDA 1: Instalar la dependencia
"""

!pip install pandas numpy scikit-learn

"""CELDA 2: Importar las librerias"""

import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.impute import SimpleImputer

"""CELDA 3: Cargar el dataset"""

from google.colab import files

uploaded = files.upload()

df = pd.read_csv("AI_Impact_on_Jobs_2030.csv")

df.head()

"""CELDA 4: Exploracion Inicial"""

print("Dimensiones:")
print(df.shape)

print("\nInformación:")
print(df.info())

print("\nValores nulos:")
print(df.isnull().sum())

"""CELDA 5: Eliminar columnas innecesarias"""

df = df.drop(columns=['Employee_ID'])

df.head()

"""CELDA 6: Separar variables numericas y categoricas"""

numericas = df.select_dtypes(include=['int64','float64']).columns.tolist()

categoricas = df.select_dtypes(include=['object']).columns.tolist()

print("Numéricas:")
print(numericas)

print("\nCategóricas:")
print(categoricas)

"""CELDA 7: Definir la variable objetivo"""

target = "Hiring_Trend_2026"

X = df.drop(columns=[target])
y = df[target]

"""CELDA 8: Actualizar listas de columnas"""

numericas = X.select_dtypes(include=['int64','float64']).columns.tolist()

categoricas = X.select_dtypes(include=['object']).columns.tolist()

"""CELDA 9: Pipeline de normalización"""

numeric_transformer = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', StandardScaler())
    ]
)

categorical_transformer = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('encoder', OneHotEncoder(handle_unknown='ignore'))
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numericas),
        ('cat', categorical_transformer, categoricas)
    ]
)

"""CELDA 10: Ejecutar la normalización"""

X_procesado = preprocessor.fit_transform(X)

print("Dataset procesado:")
print(X_procesado.shape)

"""CELDA 11: Convertir a DataFrame"""

columnas_cat = preprocessor.named_transformers_['cat']\
                           .named_steps['encoder']\
                           .get_feature_names_out(categoricas)

columnas_finales = list(numericas) + list(columnas_cat)

X_final = pd.DataFrame(
    X_procesado.toarray() if hasattr(X_procesado, "toarray") else X_procesado,
    columns=columnas_finales
)

X_final.head()

"""CELDA 12: Guardar el dataset normalizado"""

X_final["target"] = y.values

X_final.to_csv(
    "dataset_normalizado.csv",
    index=False
)

print("Dataset normalizado guardado correctamente.")

"""CELDA 13: Descargar el dataset normalizado"""

from google.colab import files

files.download('dataset_normalizado.csv')